---
# Something that isn't a hook (experimenting)
apiVersion: v1
kind: ConfigMap
metadata:
  name: dummy
data: {}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-cluster-{{ .Release.Name }}
  namespace: clusters
spec:
  template:
    metadata:
      name: create-cluster-{{ .Release.Name }}
      annotations:
        argocd.argoproj.io/hook: Sync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
    spec:
      serviceAccountName: cluster-creator-sa
      restartPolicy: Never
      backoffLimit: 0
      containers:
        - name: hypershift
          image: quay.io/hypershift/hypershift-operator:4.15
          args:
            - create
            - cluster
            - aws
            - --name
            - {{ .Release.Name }}
            - --infra-id
            - {{ .Release.Name | trunc -12 }}
            - --secret-creds
            - hypershift-creds
            - --region
            - us-east-2
            - --control-plane-availability-policy
            - SingleReplica
            - --infra-availability-policy
            - SingleReplica
            - --arch
            - "{{ .Values.ocpArch }}"
            - --release-image
            - quay.io/openshift-release-dev/ocp-release:{{ .Values.ocpVersion }}-multi
            - --node-pool-replicas
            - "2"
            - --wait

---
apiVersion: batch/v1
kind: Job
metadata:
  name: destroy-cluster-{{ .Release.Name }}
  namespace: clusters
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    metadata:
      name: destroy-cluster-{{ .Release.Name }}
    spec:
      serviceAccountName: cluster-creator-sa
      restartPolicy: Never
      containers:
        - name: hypershift
          image: quay.io/hypershift/hypershift-operator:4.15
          args:
            - destroy
            - cluster
            - aws
            - --name
            - {{ .Release.Name }}
            - --infra-id
            - {{ .Release.Name | trunc -12 }}
            - --secret-creds
            - hypershift-creds
            - --region
            - us-east-2
